### ISSUE TITLE
Service files are not present

### ISSUE THREAD

**Issue by madhu-korada** [MIT-SPARK/Kimera-PGMO#1]
In the instructions there are some ros service calls for saving the mesh, trajectory and dgrf. But they are not present in current repository. Are they yet to be added? 

Thanks.

**Comment by yunzc** [comment]
Hi, the callbacks are defined around [here](https://github.com/MIT-SPARK/Kimera-PGMO/blob/master/src/KimeraPgmo.cpp#L367).
It's just an empty service since no input is required to trigger the save. They should be saved to the output path you defined in the [launch file](https://github.com/MIT-SPARK/Kimera-PGMO/blob/master/launch/kimera_pgmo.launch#L8).
